# This is a basic workflow to help you get started with Actions

name: package

on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "package"
 package:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install      
    - name: Npm build js and css
      run: npm run build
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: tag
      run:  |
        echo "tag version ${{ steps.package-version.outputs.current-version}}"
        git tag ${{ steps.package-version.outputs.current-version}}
        git push origin --tags
    - name: Npm publish version
      run: npm publish --access public
